# Generated by Django 3.1.7 on 2021-03-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
